#!/usr/bin/with-contenv bashio
# Populates config/.env and config/speakers.json from the add-on's Configuration
# tab, then hands off to the same server.js every other deployment method runs.
# This is the ONLY job this wrapper does — MASS_TOKEN login, the SUPERVISOR_TOKEN
# restart cascade, and Ingress-relative fetches are all native in the app itself.

CONFIG_PATH=/app/config
ENV_FILE="${CONFIG_PATH}/.env"

# No speakers.json handling here on purpose — v4 auto-discovery (server.js)
# derives the subnet from MASS_IP and finds speakers itself on every boot.
# host_network: true in config.yaml is what gives it real LAN access to do so.

bashio::log.info "Writing config/.env from add-on options..."

{
    echo "# .env file format: v4.0"
    echo "# Auto-generated by the Home Assistant add-on wrapper on every start."
    echo "# Edit values in the add-on's Configuration tab, not this file directly."
    echo ""
    echo "APP_IP=$(bashio::config 'app_ip')"
    echo "APP_PORT=3000"
    echo ""
    echo "MASS_IP=$(bashio::config 'mass_ip')"
    echo "MASS_PORT=$(bashio::config 'mass_port')"
    echo "MASS_TOKEN=$(bashio::config 'mass_token')"
    echo "MASS_USERNAME=$(bashio::config 'mass_username')"
    echo "MASS_PASSWORD=$(bashio::config 'mass_password')"
    echo "MASS_CONTAINER_NAME=$(bashio::config 'mass_container_name')"
    echo ""
    echo "BOSE_PORT=$(bashio::config 'bose_port')"
    echo "TRUST_PROXY=true"
} > "${ENV_FILE}"

export TZ
TZ="$(bashio::supervisor.timezone)"
bashio::log.info "Timezone set from Home Assistant Supervisor: ${TZ}"

bashio::log.info "Starting Bose SoundTouch Hybrid..."
cd /app || exit 1
exec node server.js
